import '../styles/globals.scss';
import type { AppProps } from 'next/app';
import { LoadingProvider } from '../utils/context/LoadingContext';
import Loader from '../components/common/Loader';
import Head from 'next/head';
import React, { useState } from 'react';
import Layout from '../components/common/Layout';
import { useRouter } from 'next/router';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { Hydrate, QueryClient, QueryClientProvider } from 'react-query';

function MyApp({
  Component,
  pageProps,
}: AppProps<{ dehydratedState: unknown }>) {
  const { pathname } = useRouter();
  const [queryClient] = useState(() => new QueryClient());

  return (
    <QueryClientProvider client={queryClient}>
      <Hydrate state={pageProps.dehydratedState}>
        <LoadingProvider>
          <div className="home">
            <Head>
              <title>Gamely</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <ToastContainer />
            {pathname === '/login' || pathname === '/register' ? (
              <>
                <Loader />
                <Component {...pageProps} />
              </>
            ) : (
              <Layout>
                <Component {...pageProps} />
              </Layout>
            )}
          </div>
        </LoadingProvider>
      </Hydrate>
    </QueryClientProvider>
  );
}

export default MyApp;
